name: new-ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.3
      - name: build docker image
        run: docker build -t lidorlg/python-flask .
      - name: list images
        run: docker images
      - name: docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}  
      - name: push Docker Hub
        run: docker push lidorlg/python-flask
      - name: print variable course
        run: "echo the course variable is : ${{ vars.COURSE }}"
      - name: print log level variable
        run: "echo the log level is : ${{ vars.LOG_LEVEL }}"
